version: "3.8"

services:
  coverage_serve_nginx:
    image: nginx:latest
    container_name: coverage_serve_nginx
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 2000:80
  coverage_php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coverage_php-fpm
    volumes:
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./laravelApp:/var/www/html
    working_dir: /var/www/html
    stdin_open: true
    tty: true
volumes:
  pgdata:
    driver: local